import { test, expect } from '@playwright/test';

test('Bai tap tong hop', async ({ page }) => {
    // await page.goto('https://demoapp-sable-gamma.vercel.app')
    // await page.getByRole('link', { name: 'Bài 2: Playwright Locators' }).click()
    // await page.getByRole('button', { name: 'CSS Selector' }).click()
    await page.goto('https://demoapp-sable-gamma.vercel.app/')
    await page.getByRole('link', {name: 'Bài 2: Playwright Locators'}).click()
    await page.getByRole('button', {name: '🎯 Bài tập Tổng hợp'}).click()
    
    //const addToCartButon = page.locator('//button[@type="button" and contains(.,"Add to Cart")]')
    //const cau1_2 = page.locator('//div[@data-category="electronics"]')
    //const cau1_3 = page.locator('//div[@data-category="clothing" and @data-price="49"]')
    // const cau1_4 = page.locator('div.product-grid > div').filter({hasText: "iPhone"})
    // await cau1_4.highlight()
    //await page.locator('div.product-grid > div').filter({has: page.locator('//div[@class="ant-card-head-title" and contains(., "New")]')}).highlight()
    // const cau1_6 = page.locator('//button[@type="button" and contains(., "Analytics")]')
    // await cau1_6.click()

    // const cau2_1 = page.locator('//div[@data-role="admin" and @data-status="active"]')
    // await cau2_1.highlight()
    // const cau2_2 = page.locator('//button[@type="button" and (contains(.,"Edit") or contains(.,"Delete"))]')
    // await cau2_2.highlight()
    // const cau2_3 = page.locator('//div[contains(@class,"user-card")]').filter({hasText: "John"})
    // await cau2_3.highlight()
    // const cau2_4 = page.locator('//div[contains(@class,"user-card")]').filter({hasNot: page.locator('//button[@type="button" and contains(.,"Delete")]')})
    // await cau2_4.highlight()
    // const cau2_5 = page.locator('//button[contains(.,"Add New User")]')
    // await cau2_5.click()
    // const cau2_6 = page.locator('//div[@data-role="user"]').filter({has: page.locator('//span[contains(text(),"Inactive")]')})
    // await cau2_6.highlight()

    // const cau3_1 = page.locator('//div[contains(@class,"form-group")]').filter({has: page.locator('//div[contains(@class,"ant-form-item-explain-error")]')})
    // await cau3_1.highlight()
    // const cau3_2 = page.locator('//div[contains(@class,"form-group")]').filter({hasNot: page.locator('//div[contains(@class,"ant-form-item-explain-error")]')})
    // await cau3_2.highlight()
    // const cau3_3 = page.locator('//div[@class="ant-form-item-explain-error"]//ancestor::div[contains(@class,"form-group")]//input[@type="email" and @placeholder="Enter your email"]')
    // await cau3_3.highlight()
    // const cau3_4 = page.locator('//div[@class="ant-form-item-explain-error"]')
    // await cau3_4.highlight()
    // const cau3_5 = page.locator('//div[@class="ant-form-item-explain-success"]')
    // await cau3_5.highlight()
    // const cau3_6 = page.locator('//div[@class="exercise-html" and contains(.,"📝 User Registration Form")]//button[contains(.,"Submit Registration")]')
    // await cau3_6.click()
    const cau3_7 = page.locator('//div[contains(@class,"form-group")]').filter({has: page.locator('//label[@title="🔒 Password"]')})
    await cau3_7.highlight()
    await page.pause()
});